source 'https://rubygems.org'
gem 'tabulous', :path => "../../../.."
gem 'sqlite3', '>= 1.3.9'
group :test, :development do
  gem "rspec-rails"
end
group :test do
  gem 'capybara', "~> 2.0.2"
  gem 'launchy'
end
gem 'rails', '~> 4.0.5'
gem 'sass-rails',   '~> 4.0.2'
gem 'bootstrap-sass', '~> 3.0.2.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
group :test do
  gem 'turn', :require => false
  gem 'minitest'
end
