source 'https://rubygems.org'
gem "tabulous", :path => "../../../.."
gem "sqlite3", ">= 1.3.7"
gem "rails", "~> 3.1.0"
group :assets do
  gem "sass-rails", "~> 3.1.4"
  gem "coffee-rails", "~> 3.1.1"
  gem "uglifier", ">= 1.0.3"
end

gem "jquery-rails"
group :test do
  gem "capybara", "~> 2.0.2"
  gem "launchy"
  gem "turn", :require => false
  gem "minitest"
end

group :test, :development do
  gem "rspec-rails"
end
