source 'https://rubygems.org'
gem 'tabulous', :path => "../../../.."
gem 'sqlite3', '>= 1.3.7'
group :test, :development do
  gem "rspec-rails"
end
group :test do
  gem 'capybara', "~> 2.0.2"
  gem 'launchy'
end
gem 'rails', '~> 4.0.0.rc1'
group :assets do
  gem 'sass-rails',   '~> 4.0.0.rc1'
  gem 'bootstrap-sass', '~> 2.3.1.0'
  gem 'coffee-rails', '~> 4.0.0.rc1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.0.1'
group :test do
  gem 'turn', :require => false
  gem 'minitest'
end
