source 'https://rubygems.org'
gem 'tabulous', :path => "../../../.."
gem 'sqlite3', '>= 1.3.9'
group :test, :development do
  gem "rspec-rails"
end
group :test do
  gem 'capybara', "~> 2.0.2"
  gem 'launchy'
end
gem 'rails', '~> 3.0.0'
