#!/usr/bin/env ruby

# Run a command for all test apps.  Examples:
#
#  $ script/for_all_test_apps bundle install
#  $ script/for_all_test_apps bundle exec rake db:migrate
#  $ script/for_all_test_apps bundle exec rake test

require 'colored'
require 'rake' # in order to get the nice sh method, which allows system
               # command output to be streamed in real time
include FileUtils

command = ARGV.join(' ')

Dir['spec/applications/*/rails*'].each do |filename|
  if File.directory?(filename)
    name = filename.split('/')[-2..-1].join('/')
    print "Running".magenta
    print " #{command} ".yellow
    print "in test app".magenta
    print " #{name} ".yellow
    puts
    puts sh "cd #{filename} && #{command}"
  end
end
