source 'https://rubygems.org'
gem 'tabulous', :path => "../../../.."
gem 'sqlite3', '>= 1.3.9'
group :test, :development do
  gem "rspec-rails"
end
group :test do
  gem 'capybara', "~> 2.2.0"
  gem 'launchy'
end
gem 'rails', '~> 4.2.0'
gem 'sass-rails',   '~> 5.0'
gem 'bootstrap-sass', '~> 3.0.2.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
group :test do
  gem 'turn', :require => false
  gem 'minitest'
end
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
